// Traducción de nombres de selecciones (inglés de The Odds API -> castellano).
// Solo afecta a la presentación; en la base de datos se guarda el nombre original.
import type { Match } from './database.types'

const TEAMS: Record<string, string> = {
  // Europa
  Spain: 'España',
  England: 'Inglaterra',
  France: 'Francia',
  Germany: 'Alemania',
  Portugal: 'Portugal',
  Netherlands: 'Países Bajos',
  Belgium: 'Bélgica',
  Italy: 'Italia',
  Croatia: 'Croacia',
  Switzerland: 'Suiza',
  Denmark: 'Dinamarca',
  Sweden: 'Suecia',
  Norway: 'Noruega',
  Poland: 'Polonia',
  Serbia: 'Serbia',
  Austria: 'Austria',
  'Czech Republic': 'República Checa',
  Czechia: 'Chequia',
  Turkey: 'Turquía',
  Türkiye: 'Turquía',
  Ukraine: 'Ucrania',
  Wales: 'Gales',
  Scotland: 'Escocia',
  'Republic of Ireland': 'Irlanda',
  Ireland: 'Irlanda',
  'Northern Ireland': 'Irlanda del Norte',
  Greece: 'Grecia',
  Hungary: 'Hungría',
  Romania: 'Rumanía',
  Slovakia: 'Eslovaquia',
  Slovenia: 'Eslovenia',
  Russia: 'Rusia',
  Finland: 'Finlandia',
  Iceland: 'Islandia',
  Albania: 'Albania',
  'North Macedonia': 'Macedonia del Norte',
  Montenegro: 'Montenegro',
  'Bosnia and Herzegovina': 'Bosnia y Herzegovina',
  Bulgaria: 'Bulgaria',
  Kosovo: 'Kosovo',
  Georgia: 'Georgia',
  Armenia: 'Armenia',
  Azerbaijan: 'Azerbaiyán',
  Belarus: 'Bielorrusia',
  Moldova: 'Moldavia',
  Latvia: 'Letonia',
  Lithuania: 'Lituania',
  Estonia: 'Estonia',
  Luxembourg: 'Luxemburgo',
  Cyprus: 'Chipre',
  Malta: 'Malta',
  'Faroe Islands': 'Islas Feroe',
  Gibraltar: 'Gibraltar',
  Andorra: 'Andorra',
  'San Marino': 'San Marino',
  Liechtenstein: 'Liechtenstein',

  // Sudamérica
  Brazil: 'Brasil',
  Argentina: 'Argentina',
  Uruguay: 'Uruguay',
  Colombia: 'Colombia',
  Ecuador: 'Ecuador',
  Peru: 'Perú',
  Chile: 'Chile',
  Paraguay: 'Paraguay',
  Venezuela: 'Venezuela',
  Bolivia: 'Bolivia',

  // Concacaf
  'United States': 'Estados Unidos',
  USA: 'Estados Unidos',
  Mexico: 'México',
  Canada: 'Canadá',
  'Costa Rica': 'Costa Rica',
  Panama: 'Panamá',
  Honduras: 'Honduras',
  Jamaica: 'Jamaica',
  'El Salvador': 'El Salvador',
  Guatemala: 'Guatemala',
  'Trinidad and Tobago': 'Trinidad y Tobago',
  Nicaragua: 'Nicaragua',
  Cuba: 'Cuba',
  'Dominican Republic': 'República Dominicana',
  Curaçao: 'Curazao',
  Haiti: 'Haití',
  Suriname: 'Surinam',
  Guyana: 'Guyana',
  Belize: 'Belice',

  // África
  Morocco: 'Marruecos',
  Senegal: 'Senegal',
  Ghana: 'Ghana',
  Nigeria: 'Nigeria',
  Cameroon: 'Camerún',
  'Ivory Coast': 'Costa de Marfil',
  "Côte d'Ivoire": 'Costa de Marfil',
  Egypt: 'Egipto',
  Tunisia: 'Túnez',
  Algeria: 'Argelia',
  'South Africa': 'Sudáfrica',
  Mali: 'Malí',
  'Burkina Faso': 'Burkina Faso',
  'DR Congo': 'RD Congo',
  'Congo DR': 'RD Congo',
  'Cape Verde': 'Cabo Verde',
  Angola: 'Angola',
  Zambia: 'Zambia',
  Kenya: 'Kenia',
  Gabon: 'Gabón',
  Guinea: 'Guinea',
  Benin: 'Benín',
  Madagascar: 'Madagascar',
  Mauritania: 'Mauritania',
  Namibia: 'Namibia',
  'Equatorial Guinea': 'Guinea Ecuatorial',
  Mozambique: 'Mozambique',
  Tanzania: 'Tanzania',
  Uganda: 'Uganda',

  // Asia / Oceanía
  Japan: 'Japón',
  'South Korea': 'Corea del Sur',
  'Korea Republic': 'Corea del Sur',
  'North Korea': 'Corea del Norte',
  'Korea DPR': 'Corea del Norte',
  Australia: 'Australia',
  Iran: 'Irán',
  'IR Iran': 'Irán',
  'Saudi Arabia': 'Arabia Saudí',
  Qatar: 'Catar',
  Uzbekistan: 'Uzbekistán',
  Jordan: 'Jordania',
  Iraq: 'Irak',
  'United Arab Emirates': 'Emiratos Árabes Unidos',
  UAE: 'Emiratos Árabes Unidos',
  China: 'China',
  'China PR': 'China',
  Indonesia: 'Indonesia',
  Thailand: 'Tailandia',
  Vietnam: 'Vietnam',
  India: 'India',
  Bahrain: 'Baréin',
  Oman: 'Omán',
  Kuwait: 'Kuwait',
  Lebanon: 'Líbano',
  Syria: 'Siria',
  Palestine: 'Palestina',
  Malaysia: 'Malasia',
  Philippines: 'Filipinas',
  Singapore: 'Singapur',
  Myanmar: 'Birmania',
  Tajikistan: 'Tayikistán',
  Turkmenistan: 'Turkmenistán',
  Kyrgyzstan: 'Kirguistán',
  'Hong Kong': 'Hong Kong',
  'New Zealand': 'Nueva Zelanda',
  Israel: 'Israel',
}

export function teamName(en: string): string {
  return TEAMS[en] ?? en
}

// Devuelve una copia del partido con los nombres de equipo en castellano.
export function localizeMatch(m: Match): Match {
  return { ...m, home_team: teamName(m.home_team), away_team: teamName(m.away_team) }
}
